-- AlterTable
ALTER TABLE "DocumentsInformation" ALTER COLUMN "propertyDoc" SET DEFAULT false,
ALTER COLUMN "CIorRIF" SET DEFAULT false,
ALTER COLUMN "ownerCIorRIF" SET DEFAULT false,
ALTER COLUMN "spouseCIorRIF" SET DEFAULT false,
ALTER COLUMN "isCatastralRecordSameOwner" SET DEFAULT false,
ALTER COLUMN "condominiumSolvency" SET DEFAULT false,
ALTER COLUMN "mainProperty" SET DEFAULT false,
ALTER COLUMN "mortgageRelease" DROP NOT NULL,
ALTER COLUMN "condominiumSolvencyDetails" DROP NOT NULL,
ALTER COLUMN "power" DROP NOT NULL,
ALTER COLUMN "successionDeclaration" DROP NOT NULL,
ALTER COLUMN "courtRulings" DROP NOT NULL,
ALTER COLUMN "catastralRecordYear" DROP NOT NULL,
ALTER COLUMN "attorneyEmail" DROP NOT NULL,
ALTER COLUMN "attorneyPhone" DROP NOT NULL,
ALTER COLUMN "attorneyFirstName" DROP NOT NULL,
ALTER COLUMN "attorneyLastName" DROP NOT NULL;

-- AlterTable
ALTER TABLE "GeneralInformation" ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "propertyCondition" DROP NOT NULL,
ALTER COLUMN "handoverKeys" SET DEFAULT false,
ALTER COLUMN "termsAndConditionsAccepted" SET DEFAULT false,
ALTER COLUMN "antiquity" DROP NOT NULL,
ALTER COLUMN "zoning" DROP NOT NULL,
ALTER COLUMN "amountOfFloors" DROP NOT NULL,
ALTER COLUMN "propertiesPerFloor" DROP NOT NULL,
ALTER COLUMN "typeOfWork" DROP NOT NULL,
ALTER COLUMN "isFurnished" SET DEFAULT false,
ALTER COLUMN "isOccupiedByPeople" SET DEFAULT false;

-- AlterTable
ALTER TABLE "LocationInformation" ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "nomenclature" DROP NOT NULL,
ALTER COLUMN "tower" DROP NOT NULL,
ALTER COLUMN "amountOfFloors" DROP NOT NULL,
ALTER COLUMN "isClosedStreet" DROP NOT NULL,
ALTER COLUMN "municipality" DROP NOT NULL,
ALTER COLUMN "urbanization" DROP NOT NULL,
ALTER COLUMN "avenue" DROP NOT NULL,
ALTER COLUMN "street" DROP NOT NULL,
ALTER COLUMN "buildingShoppingCenter" DROP NOT NULL,
ALTER COLUMN "buildingNumber" DROP NOT NULL,
ALTER COLUMN "floor" DROP NOT NULL,
ALTER COLUMN "referencePoint" DROP NOT NULL,
ALTER COLUMN "howToGet" DROP NOT NULL,
ALTER COLUMN "trunkNumber" DROP NOT NULL,
ALTER COLUMN "trunkLevel" DROP NOT NULL,
ALTER COLUMN "parkingNumber" DROP NOT NULL,
ALTER COLUMN "parkingLevel" DROP NOT NULL;

-- AlterTable
ALTER TABLE "NegotiationInfomation" ALTER COLUMN "minimumNegotiation" DROP NOT NULL,
ALTER COLUMN "client" DROP NOT NULL,
ALTER COLUMN "reasonToSellOrRent" DROP NOT NULL,
ALTER COLUMN "partOfPayment" DROP NOT NULL,
ALTER COLUMN "mouthToMouth" SET DEFAULT false,
ALTER COLUMN "realStateGroups" SET DEFAULT false,
ALTER COLUMN "realStateWebPages" SET DEFAULT false,
ALTER COLUMN "socialMedia" SET DEFAULT false,
ALTER COLUMN "publicationOnBuilding" SET DEFAULT false,
ALTER COLUMN "ownerPaysCommission" DROP NOT NULL,
ALTER COLUMN "rentCommission" DROP NOT NULL,
ALTER COLUMN "sellCommission" DROP NOT NULL,
ALTER COLUMN "realStateAdviser" DROP NOT NULL;
